image: node:22

variables:
  npm_config_minimum_release_age: "0"

pages:
  stage: deploy

  before_script:
    - corepack enable
    - corepack prepare pnpm@10.17.1 --activate
    - pnpm install --no-frozen-lockfile

  script:
    - pnpm build
    - mv dist public

  artifacts:
    paths:
      - public

  only:
    - main